# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages

baseurl: "/SOEE5010_Python"  # Replace with name of repo
#baseurl: "."  # Replace with name of repo
subbaseurl: ".."

markdown: kramdown

highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

collections:
  notes:
    output: true
  workshops:
    output: true

defaults:
  -
    scope:
      path: ""  # All files
    values:
      layout: default
  -
    scope:
      path: ""  # All files
      type: "notes"
    values:
      category: note
      layout: note
  -
    scope:
      path: ""  # All files
      type: "workshops"
    values:
      category: workshop
      layout: workshop
